directory: ~/Music
library: ~/Music/beets.db

import:
  log: beets.log
  copy: yes
  write: yes

plugins:
  - fetchart
  - embedart
  - duplicates
  - deezer
  - lyrics
  - discogs

fetchart:
  auto: yes
  sources:
    - "*"

embedart:
  auto: yes

paths:
  default: "$albumartist/($year) $album/$track. $title"

ui:
  color: yes
